/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.EdFiAdmin.Client.Client.OpenAPIDateConverter;

namespace EdGraph.EdFiAdmin.Client.Model
{
    /// <summary>
    /// Defines EdfiAdminApi.EdfiAdmin.V1.DatabaseTier
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EdfiAdminApiEdfiAdminV1DatabaseTier
    {
        /// <summary>
        /// Enum GeneralPurpose for value: GeneralPurpose
        /// </summary>
        [EnumMember(Value = "GeneralPurpose")]
        GeneralPurpose = 1,

        /// <summary>
        /// Enum BusinessCritical for value: BusinessCritical
        /// </summary>
        [EnumMember(Value = "BusinessCritical")]
        BusinessCritical = 2
    }

}
