/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.EdFiAdmin.Client.Client.OpenAPIDateConverter;

namespace EdGraph.EdFiAdmin.Client.Model
{
    /// <summary>
    /// EdfiAdminApiEdfiAdminV1EdFiConnectionTier
    /// </summary>
    [DataContract(Name = "EdfiAdminApi.EdfiAdmin.V1.EdFiConnectionTier")]
    public partial class EdfiAdminApiEdfiAdminV1EdFiConnectionTier : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdfiAdminApiEdfiAdminV1EdFiConnectionTier" /> class.
        /// </summary>
        /// <param name="tierId">tierId.</param>
        /// <param name="tierName">tierName.</param>
        /// <param name="odsApiConnection">odsApiConnection.</param>
        /// <param name="sqlConnection">sqlConnection.</param>
        public EdfiAdminApiEdfiAdminV1EdFiConnectionTier(string tierId = default(string), string tierName = default(string), EdfiAdminApiEdfiAdminV1TierOdsApiConnection odsApiConnection = default(EdfiAdminApiEdfiAdminV1TierOdsApiConnection), EdfiAdminApiEdfiAdminV1TierSqlConnection sqlConnection = default(EdfiAdminApiEdfiAdminV1TierSqlConnection))
        {
            this.TierId = tierId;
            this.TierName = tierName;
            this.OdsApiConnection = odsApiConnection;
            this.SqlConnection = sqlConnection;
        }

        /// <summary>
        /// Gets or Sets TierId
        /// </summary>
        [DataMember(Name = "tierId", EmitDefaultValue = true)]
        public string TierId { get; set; }

        /// <summary>
        /// Gets or Sets TierName
        /// </summary>
        [DataMember(Name = "tierName", EmitDefaultValue = true)]
        public string TierName { get; set; }

        /// <summary>
        /// Gets or Sets OdsApiConnection
        /// </summary>
        [DataMember(Name = "odsApiConnection", EmitDefaultValue = false)]
        public EdfiAdminApiEdfiAdminV1TierOdsApiConnection OdsApiConnection { get; set; }

        /// <summary>
        /// Gets or Sets SqlConnection
        /// </summary>
        [DataMember(Name = "sqlConnection", EmitDefaultValue = false)]
        public EdfiAdminApiEdfiAdminV1TierSqlConnection SqlConnection { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdfiAdminApiEdfiAdminV1EdFiConnectionTier {\n");
            sb.Append("  TierId: ").Append(TierId).Append("\n");
            sb.Append("  TierName: ").Append(TierName).Append("\n");
            sb.Append("  OdsApiConnection: ").Append(OdsApiConnection).Append("\n");
            sb.Append("  SqlConnection: ").Append(SqlConnection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
