/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.EdFiAdmin.Client.Client;
using EdGraph.EdFiAdmin.Client.Api;
// uncomment below to import models
//using EdGraph.EdFiAdmin.Client.Model;

namespace EdGraph.EdFiAdmin.Client.Test.Api
{
    /// <summary>
    ///  Class for testing InstancesReportsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InstancesReportsApiTests : IDisposable
    {
        private InstancesReportsApi instance;

        public InstancesReportsApiTests()
        {
            instance = new InstancesReportsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstancesReportsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InstancesReportsApi
            //Assert.IsType<InstancesReportsApi>(instance);
        }

        /// <summary>
        /// Test GenerateReportsAsync
        /// </summary>
        [Fact]
        public void GenerateReportsAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GenerateReportsAsync(tenantId, instanceId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1GenerateReportsResponse>(response);
        }

        /// <summary>
        /// Test GetReportsStatusAsync
        /// </summary>
        [Fact]
        public void GetReportsStatusAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetReportsStatusAsync(tenantId, instanceId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1ReportsStatusResponse>(response);
        }

        /// <summary>
        /// Test GetSchoolsByTypeReportAsync
        /// </summary>
        [Fact]
        public void GetSchoolsByTypeReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetSchoolsByTypeReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse>(response);
        }

        /// <summary>
        /// Test GetStudentEconomicSituationReportAsync
        /// </summary>
        [Fact]
        public void GetStudentEconomicSituationReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetStudentEconomicSituationReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StudentEconomicSituationReportResponse>(response);
        }

        /// <summary>
        /// Test GetStudentEnrollmentByEthnicityReport
        /// </summary>
        [Fact]
        public void GetStudentEnrollmentByEthnicityReportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetStudentEnrollmentByEthnicityReport(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StudentEnrollmentByEthnicityReportResponse>(response);
        }

        /// <summary>
        /// Test GetStudentEnrollmentByGenderReportAsync
        /// </summary>
        [Fact]
        public void GetStudentEnrollmentByGenderReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetStudentEnrollmentByGenderReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StudentEnrollmentByGenderReportResponse>(response);
        }

        /// <summary>
        /// Test GetStudentEnrollmentByRaceReportAsync
        /// </summary>
        [Fact]
        public void GetStudentEnrollmentByRaceReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetStudentEnrollmentByRaceReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StudentEnrollmentByRaceReportResponse>(response);
        }

        /// <summary>
        /// Test GetStudentsByProgramReportAsync
        /// </summary>
        [Fact]
        public void GetStudentsByProgramReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetStudentsByProgramReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StudentsByProgramReportResponse>(response);
        }

        /// <summary>
        /// Test GetTotalEnrollmentsReportAsync
        /// </summary>
        [Fact]
        public void GetTotalEnrollmentsReportAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int localEducationAgencyId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTotalEnrollmentsReportAsync(tenantId, instanceId, localEducationAgencyId, apiVersion, xVersion);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1TotalEnrollmentsReportResponse>(response);
        }
    }
}
