/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.EdFiAdmin.Client.Client;
using EdGraph.EdFiAdmin.Client.Api;
// uncomment below to import models
//using EdGraph.EdFiAdmin.Client.Model;

namespace EdGraph.EdFiAdmin.Client.Test.Api
{
    /// <summary>
    ///  Class for testing InstanceOnboardingStepsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InstanceOnboardingStepsApiTests : IDisposable
    {
        private InstanceOnboardingStepsApi instance;

        public InstanceOnboardingStepsApiTests()
        {
            instance = new InstanceOnboardingStepsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstanceOnboardingStepsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InstanceOnboardingStepsApi
            //Assert.IsType<InstanceOnboardingStepsApi>(instance);
        }

        /// <summary>
        /// Test CreateInstanceOnboardingStepAsync
        /// </summary>
        [Fact]
        public void CreateInstanceOnboardingStepAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest? edfiAdminApiEdfiAdminV1CreateOnboardingStepRequest = null;
            //var response = instance.CreateInstanceOnboardingStepAsync(tenantId, instanceId, apiVersion, xVersion, edfiAdminApiEdfiAdminV1CreateOnboardingStepRequest);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1InstanceUpdatedResponse>(response);
        }

        /// <summary>
        /// Test UpdateInstanceOnboardingStepAsync
        /// </summary>
        [Fact]
        public void UpdateInstanceOnboardingStepAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string instanceId = null;
            //int stepNumber = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //EdfiAdminApiEdfiAdminV1UpdateOnboardingStepRequest? edfiAdminApiEdfiAdminV1UpdateOnboardingStepRequest = null;
            //var response = instance.UpdateInstanceOnboardingStepAsync(tenantId, instanceId, stepNumber, apiVersion, xVersion, edfiAdminApiEdfiAdminV1UpdateOnboardingStepRequest);
            //Assert.IsType<EdfiAdminApiEdfiAdminV1InstanceUpdatedResponse>(response);
        }
    }
}
