/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse
        //private EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse instance;

        public EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponseTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse
            //instance = new EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse
            //Assert.IsType<EdfiAdminApiEdfiAdminV1RegenerateApiClientSecretResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'ApiClientId'
        /// </summary>
        [Fact]
        public void ApiClientIdTest()
        {
            // TODO unit test for the property 'ApiClientId'
        }

        /// <summary>
        /// Test the property 'NewSecret'
        /// </summary>
        [Fact]
        public void NewSecretTest()
        {
            // TODO unit test for the property 'NewSecret'
        }
    }
}
