/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1ClaimSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1ClaimSetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1ClaimSet
        //private EdfiAdminApiEdfiAdminV1ClaimSet instance;

        public EdfiAdminApiEdfiAdminV1ClaimSetTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1ClaimSet
            //instance = new EdfiAdminApiEdfiAdminV1ClaimSet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1ClaimSet
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1ClaimSetInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1ClaimSet
            //Assert.IsType<EdfiAdminApiEdfiAdminV1ClaimSet>(instance);
        }

        /// <summary>
        /// Test the property 'ClaimSetId'
        /// </summary>
        [Fact]
        public void ClaimSetIdTest()
        {
            // TODO unit test for the property 'ClaimSetId'
        }

        /// <summary>
        /// Test the property 'ClaimSetName'
        /// </summary>
        [Fact]
        public void ClaimSetNameTest()
        {
            // TODO unit test for the property 'ClaimSetName'
        }

        /// <summary>
        /// Test the property 'IsSystemReserved'
        /// </summary>
        [Fact]
        public void IsSystemReservedTest()
        {
            // TODO unit test for the property 'IsSystemReserved'
        }

        /// <summary>
        /// Test the property 'ApplicationsCount'
        /// </summary>
        [Fact]
        public void ApplicationsCountTest()
        {
            // TODO unit test for the property 'ApplicationsCount'
        }
    }
}
