/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel
        //private EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel instance;

        public EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModelTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel
            //instance = new EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel
            //Assert.IsType<EdfiAdminApiEdfiAdminV1ClaimSetPaginatedItemsViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
