/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse
        //private EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse instance;

        public EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse
            //instance = new EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse
            //Assert.IsType<EdfiAdminApiEdfiAdminV1LocalEducationAgencyCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'LocalEducationAgency'
        /// </summary>
        [Fact]
        public void LocalEducationAgencyTest()
        {
            // TODO unit test for the property 'LocalEducationAgency'
        }
    }
}
