/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1EducationOrganizationAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1EducationOrganizationAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1EducationOrganizationAddress
        //private EdfiAdminApiEdfiAdminV1EducationOrganizationAddress instance;

        public EdfiAdminApiEdfiAdminV1EducationOrganizationAddressTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1EducationOrganizationAddress
            //instance = new EdfiAdminApiEdfiAdminV1EducationOrganizationAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1EducationOrganizationAddress
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1EducationOrganizationAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1EducationOrganizationAddress
            //Assert.IsType<EdfiAdminApiEdfiAdminV1EducationOrganizationAddress>(instance);
        }

        /// <summary>
        /// Test the property 'AddressTypeDescriptor'
        /// </summary>
        [Fact]
        public void AddressTypeDescriptorTest()
        {
            // TODO unit test for the property 'AddressTypeDescriptor'
        }

        /// <summary>
        /// Test the property 'StateAbbreviationDescriptor'
        /// </summary>
        [Fact]
        public void StateAbbreviationDescriptorTest()
        {
            // TODO unit test for the property 'StateAbbreviationDescriptor'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'StreetNumberName'
        /// </summary>
        [Fact]
        public void StreetNumberNameTest()
        {
            // TODO unit test for the property 'StreetNumberName'
        }

        /// <summary>
        /// Test the property 'LocaleDescriptor'
        /// </summary>
        [Fact]
        public void LocaleDescriptorTest()
        {
            // TODO unit test for the property 'LocaleDescriptor'
        }

        /// <summary>
        /// Test the property 'BuildingSiteNumber'
        /// </summary>
        [Fact]
        public void BuildingSiteNumberTest()
        {
            // TODO unit test for the property 'BuildingSiteNumber'
        }

        /// <summary>
        /// Test the property 'NameOfCounty'
        /// </summary>
        [Fact]
        public void NameOfCountyTest()
        {
            // TODO unit test for the property 'NameOfCounty'
        }
    }
}
