/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse
        //private EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse instance;

        public EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse
            //instance = new EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse
            //Assert.IsType<EdfiAdminApiEdfiAdminV1EdFiApplicationCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Fact]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }

        /// <summary>
        /// Test the property 'ClaimSetName'
        /// </summary>
        [Fact]
        public void ClaimSetNameTest()
        {
            // TODO unit test for the property 'ClaimSetName'
        }

        /// <summary>
        /// Test the property 'OperationalContextUri'
        /// </summary>
        [Fact]
        public void OperationalContextUriTest()
        {
            // TODO unit test for the property 'OperationalContextUri'
        }

        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Fact]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }
    }
}
