/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest
        //private EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest instance;

        public EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequestTests()
        {
            // TODO uncomment below to create an instance of EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest
            //instance = new EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest
        /// </summary>
        [Fact]
        public void EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest
            //Assert.IsType<EdFiAdminApiApplicationAccessV1UpdateApplicationAccessRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'ApiClientId'
        /// </summary>
        [Fact]
        public void ApiClientIdTest()
        {
            // TODO unit test for the property 'ApiClientId'
        }

        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
    }
}
