/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1TierSqlConnection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1TierSqlConnectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1TierSqlConnection
        //private EdfiAdminApiEdfiAdminV1TierSqlConnection instance;

        public EdfiAdminApiEdfiAdminV1TierSqlConnectionTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1TierSqlConnection
            //instance = new EdfiAdminApiEdfiAdminV1TierSqlConnection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1TierSqlConnection
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1TierSqlConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1TierSqlConnection
            //Assert.IsType<EdfiAdminApiEdfiAdminV1TierSqlConnection>(instance);
        }

        /// <summary>
        /// Test the property 'SqlServer'
        /// </summary>
        [Fact]
        public void SqlServerTest()
        {
            // TODO unit test for the property 'SqlServer'
        }

        /// <summary>
        /// Test the property 'SqlServerUserName'
        /// </summary>
        [Fact]
        public void SqlServerUserNameTest()
        {
            // TODO unit test for the property 'SqlServerUserName'
        }

        /// <summary>
        /// Test the property 'SqlServerPassword'
        /// </summary>
        [Fact]
        public void SqlServerPasswordTest()
        {
            // TODO unit test for the property 'SqlServerPassword'
        }

        /// <summary>
        /// Test the property 'AzureSubscriptionId'
        /// </summary>
        [Fact]
        public void AzureSubscriptionIdTest()
        {
            // TODO unit test for the property 'AzureSubscriptionId'
        }

        /// <summary>
        /// Test the property 'AzureResourceGroupName'
        /// </summary>
        [Fact]
        public void AzureResourceGroupNameTest()
        {
            // TODO unit test for the property 'AzureResourceGroupName'
        }

        /// <summary>
        /// Test the property 'AzureServerName'
        /// </summary>
        [Fact]
        public void AzureServerNameTest()
        {
            // TODO unit test for the property 'AzureServerName'
        }

        /// <summary>
        /// Test the property 'AzureServerElasticPoolName'
        /// </summary>
        [Fact]
        public void AzureServerElasticPoolNameTest()
        {
            // TODO unit test for the property 'AzureServerElasticPoolName'
        }
    }
}
