/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1ResourceClaim
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1ResourceClaimTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1ResourceClaim
        //private EdfiAdminApiEdfiAdminV1ResourceClaim instance;

        public EdfiAdminApiEdfiAdminV1ResourceClaimTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1ResourceClaim
            //instance = new EdfiAdminApiEdfiAdminV1ResourceClaim();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1ResourceClaim
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1ResourceClaimInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1ResourceClaim
            //Assert.IsType<EdfiAdminApiEdfiAdminV1ResourceClaim>(instance);
        }

        /// <summary>
        /// Test the property 'ResourceClaimId'
        /// </summary>
        [Fact]
        public void ResourceClaimIdTest()
        {
            // TODO unit test for the property 'ResourceClaimId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Create'
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO unit test for the property 'Create'
        }

        /// <summary>
        /// Test the property 'CreateAuthStrategy'
        /// </summary>
        [Fact]
        public void CreateAuthStrategyTest()
        {
            // TODO unit test for the property 'CreateAuthStrategy'
        }

        /// <summary>
        /// Test the property 'Read'
        /// </summary>
        [Fact]
        public void ReadTest()
        {
            // TODO unit test for the property 'Read'
        }

        /// <summary>
        /// Test the property 'ReadAuthStrategy'
        /// </summary>
        [Fact]
        public void ReadAuthStrategyTest()
        {
            // TODO unit test for the property 'ReadAuthStrategy'
        }

        /// <summary>
        /// Test the property 'Update'
        /// </summary>
        [Fact]
        public void UpdateTest()
        {
            // TODO unit test for the property 'Update'
        }

        /// <summary>
        /// Test the property 'UpdateAuthStrategy'
        /// </summary>
        [Fact]
        public void UpdateAuthStrategyTest()
        {
            // TODO unit test for the property 'UpdateAuthStrategy'
        }

        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }

        /// <summary>
        /// Test the property 'DeleteAuthStrategy'
        /// </summary>
        [Fact]
        public void DeleteAuthStrategyTest()
        {
            // TODO unit test for the property 'DeleteAuthStrategy'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
    }
}
