/*
 * Admin API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel
        //private EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel instance;

        public EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModelTests()
        {
            // TODO uncomment below to create an instance of EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel
            //instance = new EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel
        /// </summary>
        [Fact]
        public void EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel
            //Assert.IsType<EdFiOdsAdminApiFeaturesClaimSetsResourceClaimModel>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Read'
        /// </summary>
        [Fact]
        public void ReadTest()
        {
            // TODO unit test for the property 'Read'
        }
        /// <summary>
        /// Test the property 'Create'
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO unit test for the property 'Create'
        }
        /// <summary>
        /// Test the property 'Update'
        /// </summary>
        [Fact]
        public void UpdateTest()
        {
            // TODO unit test for the property 'Update'
        }
        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }
        /// <summary>
        /// Test the property 'DefaultAuthStrategiesForCRUD'
        /// </summary>
        [Fact]
        public void DefaultAuthStrategiesForCRUDTest()
        {
            // TODO unit test for the property 'DefaultAuthStrategiesForCRUD'
        }
        /// <summary>
        /// Test the property 'AuthStrategyOverridesForCRUD'
        /// </summary>
        [Fact]
        public void AuthStrategyOverridesForCRUDTest()
        {
            // TODO unit test for the property 'AuthStrategyOverridesForCRUD'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

    }

}
