/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1Onboarding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1OnboardingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1Onboarding
        //private EdfiAdminApiEdfiAdminV1Onboarding instance;

        public EdfiAdminApiEdfiAdminV1OnboardingTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1Onboarding
            //instance = new EdfiAdminApiEdfiAdminV1Onboarding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1Onboarding
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1OnboardingInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1Onboarding
            //Assert.IsType<EdfiAdminApiEdfiAdminV1Onboarding>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ProgressPercentage'
        /// </summary>
        [Fact]
        public void ProgressPercentageTest()
        {
            // TODO unit test for the property 'ProgressPercentage'
        }

        /// <summary>
        /// Test the property 'TotalSteps'
        /// </summary>
        [Fact]
        public void TotalStepsTest()
        {
            // TODO unit test for the property 'TotalSteps'
        }

        /// <summary>
        /// Test the property 'LastCompletedStep'
        /// </summary>
        [Fact]
        public void LastCompletedStepTest()
        {
            // TODO unit test for the property 'LastCompletedStep'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
    }
}
