/*
 * Admin API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdFiOdsAdminApiFeaturesAdminApiError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdFiOdsAdminApiFeaturesAdminApiErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdFiOdsAdminApiFeaturesAdminApiError
        //private EdFiOdsAdminApiFeaturesAdminApiError instance;

        public EdFiOdsAdminApiFeaturesAdminApiErrorTests()
        {
            // TODO uncomment below to create an instance of EdFiOdsAdminApiFeaturesAdminApiError
            //instance = new EdFiOdsAdminApiFeaturesAdminApiError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdFiOdsAdminApiFeaturesAdminApiError
        /// </summary>
        [Fact]
        public void EdFiOdsAdminApiFeaturesAdminApiErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdFiOdsAdminApiFeaturesAdminApiError
            //Assert.IsType<EdFiOdsAdminApiFeaturesAdminApiError>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
