/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1StateEducationAgency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1StateEducationAgencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1StateEducationAgency
        //private EdfiAdminApiEdfiAdminV1StateEducationAgency instance;

        public EdfiAdminApiEdfiAdminV1StateEducationAgencyTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1StateEducationAgency
            //instance = new EdfiAdminApiEdfiAdminV1StateEducationAgency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1StateEducationAgency
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1StateEducationAgencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1StateEducationAgency
            //Assert.IsType<EdfiAdminApiEdfiAdminV1StateEducationAgency>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'StateEducationAgencyId'
        /// </summary>
        [Fact]
        public void StateEducationAgencyIdTest()
        {
            // TODO unit test for the property 'StateEducationAgencyId'
        }

        /// <summary>
        /// Test the property 'NameOfInstitution'
        /// </summary>
        [Fact]
        public void NameOfInstitutionTest()
        {
            // TODO unit test for the property 'NameOfInstitution'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationCategoryDescriptors'
        /// </summary>
        [Fact]
        public void EducationOrganizationCategoryDescriptorsTest()
        {
            // TODO unit test for the property 'EducationOrganizationCategoryDescriptors'
        }
    }
}
