/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor
        //private EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor instance;

        public EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptorTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor
            //instance = new EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptorInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor
            //Assert.IsType<EdfiAdminApiEdfiAdminV1EducationOrganizationCategoryDescriptor>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationCategoryDescriptorId'
        /// </summary>
        [Fact]
        public void EducationOrganizationCategoryDescriptorIdTest()
        {
            // TODO unit test for the property 'EducationOrganizationCategoryDescriptorId'
        }

        /// <summary>
        /// Test the property 'CodeValue'
        /// </summary>
        [Fact]
        public void CodeValueTest()
        {
            // TODO unit test for the property 'CodeValue'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'VarNamespace'
        /// </summary>
        [Fact]
        public void VarNamespaceTest()
        {
            // TODO unit test for the property 'VarNamespace'
        }

        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Fact]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }
    }
}
