/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1GenderRepresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1GenderRepresentationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1GenderRepresentation
        //private EdfiAdminApiEdfiAdminV1GenderRepresentation instance;

        public EdfiAdminApiEdfiAdminV1GenderRepresentationTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1GenderRepresentation
            //instance = new EdfiAdminApiEdfiAdminV1GenderRepresentation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1GenderRepresentation
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1GenderRepresentationInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1GenderRepresentation
            //Assert.IsType<EdfiAdminApiEdfiAdminV1GenderRepresentation>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'PercentOfTotal'
        /// </summary>
        [Fact]
        public void PercentOfTotalTest()
        {
            // TODO unit test for the property 'PercentOfTotal'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
