/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1SyncClaimSetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1SyncClaimSetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1SyncClaimSetRequest
        //private EdfiAdminApiEdfiAdminV1SyncClaimSetRequest instance;

        public EdfiAdminApiEdfiAdminV1SyncClaimSetRequestTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1SyncClaimSetRequest
            //instance = new EdfiAdminApiEdfiAdminV1SyncClaimSetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1SyncClaimSetRequest
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1SyncClaimSetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1SyncClaimSetRequest
            //Assert.IsType<EdfiAdminApiEdfiAdminV1SyncClaimSetRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'ClaimSetId'
        /// </summary>
        [Fact]
        public void ClaimSetIdTest()
        {
            // TODO unit test for the property 'ClaimSetId'
        }

        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Fact]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }
    }
}
