/*
 * Ed-Fi Admin Api
 *
 * Ed-Fi Admin Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.EdFiAdmin.Client.Model;
using EdGraph.EdFiAdmin.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.EdFiAdmin.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse
        //private EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse instance;

        public EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponseTests()
        {
            // TODO uncomment below to create an instance of EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse
            //instance = new EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse
        /// </summary>
        [Fact]
        public void EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse
            //Assert.IsType<EdfiAdminApiEdfiAdminV1LocalEducationAgencyTableViewResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationId'
        /// </summary>
        [Fact]
        public void EducationOrganizationIdTest()
        {
            // TODO unit test for the property 'EducationOrganizationId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'NameOfInstitution'
        /// </summary>
        [Fact]
        public void NameOfInstitutionTest()
        {
            // TODO unit test for the property 'NameOfInstitution'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationCategory'
        /// </summary>
        [Fact]
        public void EducationOrganizationCategoryTest()
        {
            // TODO unit test for the property 'EducationOrganizationCategory'
        }
    }
}
